Traceback (most recent call last):
  File "/teamspace/studios/this_studio/main.py", line 12, in <module>
    area = segment_wound_area(config)
  File "/teamspace/studios/this_studio/tasks/segment_wound_area.py", line 32, in segment_wound_area
    gt = np.array(Image.open(gt_path))
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/PIL/Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/teamspace/studios/this_studio/data/subset_gt//teamspace/studios/this_studio/data/subset/'
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/main.py", line 12, in <module>
    area = segment_wound_area(config)
  File "/teamspace/studios/this_studio/tasks/segment_wound_area.py", line 32, in segment_wound_area
    gt = np.array(Image.open(gt_path))
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/PIL/Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/teamspace/studios/this_studio/data/subset_gt//teamspace/studios/this_studio/data/subset/'
